### ISSUE TITLE
Message: "[relaton-bib] WARNING: invalid relation type: supersedes"

### ISSUE THREAD

**Issue by manuel489** [relaton/relaton#79]
*This issue is related to https://github.com/metanorma/mn-samples-nist/issues/43*
When fetching references, I am constantly getting this message: 
`[relaton-bib] WARNING: invalid relation type: supersedes`

For example:
````
[relaton-iso] ("ISO/IEC 27001") fetching...
[relaton-iso] ("ISO/IEC 27001") found ISO/IEC 27001:2005
[relaton-iso] ("ISO/IEC 15408-1") fetching...
[relaton-iso] ("ISO/IEC 15408-1") found ISO/IEC 15408-1:2009
[relaton-iso] ("ISO/IEC 15408-2") fetching...
[relaton-iso] ("ISO/IEC 15408-2") found ISO/IEC 15408-2:2008
[relaton-iso] ("ISO/IEC 15408-3") fetching...
[relaton-iso] ("ISO/IEC 15408-3") found ISO/IEC 15408-3:2008
[relaton-nist] ("NIST FIPS 140-2") fetching...
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-nist] ("NIST FIPS 140-2") found FIPS 140-2
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-nist] ("NIST FIPS 180-4") fetching...
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-nist] ("NIST FIPS 180-4") found FIPS 180-4
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-nist] ("NIST FIPS 186-3") fetching...
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-nist] ("NIST FIPS 186-3") found FIPS 186-3
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-nist] ("NIST FIPS 188") fetching...
[relaton-nist] ("NIST FIPS 188") found FIPS 188
````

**Comment by andrew2net** [comment]
Fixed. Please use relaton-bib 1.2.1 and relaton-nist 1.2.1

**Comment by manuel489** [comment]
Hi @andrew2net , I'm using relaton-bib 1.2.2 and relaton-nist 1.2.1, and I'm still getting the message when compiling [800-53r4](https://raw.githubusercontent.com/metanorma/mn-samples-nist/master/sources/800-53r4/document.adoc?token=AIAR3WZ767BQAEWLEXG5WV267IBWG)

````
bundle exec metanorma -t nist -x html sources/800-53r4/document.adoc
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
Style Warning: (XML Line 000064): Hanging paragraph in clause
Style: First section of document body should be Introduction, not
...
````

**Comment by andrew2net** [comment]
Hi @manuel489, I don't have these messages when fetching "800-53r4" in relaton-nist.
Could you provide an output of the command `bundle list`? Where I can get the "sources/800-53r4/document.adoc" file?

**Comment by manuel489** [comment]
> Could you provide an output of the command bundle list? Where I can get the "sources/800-53r4/document.adoc" file?

Sure, here you are:

````
$ bundle list
Gems included by the bundle:
  * addressable (2.7.0)
  * asciidoctor (2.0.10)
  * asciimath (2.0.1)
  * bibtex-ruby (5.1.4)
  * camertron-eprun (1.1.1)
  * cldr-plurals-runtime-rb (1.0.1)
  * cnccs (0.1.6)
  * concurrent-ruby (1.1.6)
  * domain_name (0.5.20190701)
  * down (5.1.1)
  * faraday (1.0.1)
  * ffi (1.13.1)
  * ffi-compiler2 (2.0.0)
  * fontist (1.0.0)
  * gb-agencies (0.0.6)
  * git (1.7.0)
  * html2doc (1.0.3)
  * htmlentities (4.3.4)
  * http-cookie (1.0.3)
  * iev (0.2.3)
  * image_size (2.0.2)
  * iso-639 (0.3.5)
  * iso639 (1.3.2)
  * isodoc (1.1.0)
  * isoics (0.1.8)
  * latex-decode (0.3.1)
  * libmspack (0.1.0)
  * liquid (4.0.3)
  * mathml2asciimath (0.0.10)
  * metanorma (1.1.0)
  * metanorma-cc (1.4.0)
  * metanorma-cli (1.3.1)
  * metanorma-csa (1.5.0)
  * metanorma-gb (1.4.0)
  * metanorma-generic (1.5.0)
  * metanorma-iec (1.1.0)
  * metanorma-ietf (2.1.0)
  * metanorma-iho (0.1.0)
  * metanorma-iso (1.4.0)
  * metanorma-itu (1.1.0)
  * metanorma-m3aawg (1.4.0)
  * metanorma-nist (1.1.0)
  * metanorma-ogc (1.1.0)
  * metanorma-standoc (1.4.2)
  * metanorma-un (0.4.0)
  * mime-types (3.3.1)
  * mime-types-data (3.2020.0512)
  * mimemagic (0.3.5)
  * mini_portile2 (2.4.0)
  * mn2pdf (1.18)
  * mn2sts (1.2.0)
  * multipart-post (2.1.1)
  * nokogiri (1.10.9)
  * optout (0.0.2)
  * public_suffix (4.0.5)
  * rake (12.3.3)
  * rchardet (1.8.0)
  * relaton (1.2.0)
  * relaton-bib (1.2.2)
  * relaton-calconnect (1.2.0)
  * relaton-cli (1.2.0)
  * relaton-gb (1.2.0)
  * relaton-iec (1.2.0)
  * relaton-ieee (1.2.0)
  * relaton-ietf (1.2.0)
  * relaton-iev (1.0.0)
  * relaton-iho (1.2.0)
  * relaton-iso (1.2.0)
  * relaton-iso-bib (1.2.0)
  * relaton-itu (1.2.0)
  * relaton-nist (1.2.1)
  * relaton-ogc (1.2.0)
  * relaton-omg (1.2.0)
  * relaton-un (1.2.1)
  * relaton-w3c (1.2.0)
  * roman-numerals (0.3.0)
  * ruby-jing (0.0.1)
  * rubyzip (2.3.0)
  * sassc (2.4.0)
  * sterile (1.0.16)
  * thor (0.20.3)
  * thread_safe (0.3.6)
  * tokenizer (0.3.0)
  * twitter_cldr (4.4.5)
  * tzinfo (2.0.2)
  * tzinfo-data (1.2020.1)
  * unf (0.1.4)
  * unf_ext (0.0.7.7)
  * unicode2latex (0.0.3)
  * uuidtools (2.1.5)
Use `bundle info` to print more detailed information about a gem
````

**Comment by manuel489** [comment]
> UPD I found the "sources/800-53r4/document.adoc" file. Can reproduce the issue now.

Ok!

**Comment by andrew2net** [comment]
@manuel489 fixed it in relaton-nist v 1.2.2

**Comment by manuel489** [comment]
Confirmed. Thanks @andrew2net !
